defaults:
  - scope:
      path: "images"
    values:
      image: true
  - scope:
      path: "css"
    values:
      css: true
  - scope:
      path: "fonts"
    values:
      font: true
  - scope:
      path: "assets/js"
    values:
      javascript: true
  - scope:
      path: "assets"
    values:
      base: true